// SPDX-License-Identifier: MIT
// Copyright (c) 2025. Csaba Dudas (CsabaDu)

namespace Adatamiq.TestDataTypes.Patterns;

/// <summary>
/// Represents a base interface for test data that has a primary test parameter for test case result.
/// </summary>
public interface IExpected
{
    /// <summary>
    /// Gets the prefix applied to the result strings generated by the operation.
    /// </summary>
    string GetResultPrefix();

    object GetExpected();
}

public interface IExpected<out TResult>
: IExpected
where TResult : notnull
{
    /// <summary>
    /// Gets the strongly typed expected result of the test case.
    /// </summary>
    TResult Expected { get; }
}
