// SPDX-License-Identifier: MIT
// Copyright (c) 2025. Csaba Dudas (CsabaDu)

namespace Portamical.Core.TestDataTypes.Patterns;

/// <summary>
/// Represents a base interface for test data that has a primary test parameter for test case result.
/// </summary>
public interface IExpected
{
    /// <summary>
    /// Gets the prefix applied to the result strings generated by the operation.
    /// </summary>
    string GetResultPrefix();

    /// <summary>
    /// Gets the expected value for the current context or operation.
    /// </summary>
    /// <returns>An object representing the expected value. The specific type and meaning depend on the implementation and usage
    /// context.</returns>
    object GetExpected();
}

/// <summary>
/// Defines a contract for accessing the expected result of a test case in a strongly typed manner.
/// </summary>
/// <typeparam name="TResult">The type of the expected result. Must be a non-nullable type.</typeparam>
public interface IExpected<out TResult>
: IExpected
where TResult : notnull
{
    /// <summary>
    /// Gets the strongly typed expected result of the test case.
    /// </summary>
    TResult Expected { get; }
}
