// <auto-generated>
// This file was generated by a T4 template. Do not modify directly.
// Edit TestDataFactory.tt instead.
// </auto-generated>
// SPDX-License-Identifier: MIT
// Copyright (c) 2026. Csaba Dudas (CsabaDu)

using Portamical.Core.TestDataTypes.Models.General;
using Portamical.Core.TestDataTypes.Models.Specialized;

namespace Portamical.Core.Factories;

/// <summary>
/// Factory class for creating and working with test data instances.
/// </summary>
/// <remarks>
/// Provides static factory methods for creating:
/// <list type="bullet">
/// <item>Standard test data</item>
/// <item>Test data with expected return values</item>
/// <item>Test data with expected exceptions</item>
/// </list>
/// </remarks>
public static class TestDataFactory
{
    #region CreateTestData methods
    /// <summary>
    /// Creates standard test data with 1 argument(s).
    /// </summary>
    /// <typeparam name="T1">Type of the first test argument.</typeparam>
    /// <param name="definition">Description of the test scenario.</param>
    /// <param name="result">Expected result description.</param>
    /// <param name="arg1">The first test argument value.</param>
    /// <returns>A new <see cref="TestData{T1}"/> instance.</returns>
    public static TestData<T1> CreateTestData<T1>(
        string definition,
        string result,
        T1? arg1)
    => new(
        definition,
        result,
        arg1);

    /// <summary>
    /// Creates standard test data with 2 argument(s).
    /// </summary>
    /// <typeparam name="T1">Type of the first test argument.</typeparam>
    /// <typeparam name="T2">Type of the second test argument.</typeparam>
    /// <param name="definition">Description of the test scenario.</param>
    /// <param name="result">Expected result description.</param>
    /// <param name="arg1">The first test argument value.</param>
    /// <param name="arg2">The second test argument value.</param>
    /// <returns>A new <see cref="TestData{T1, T2}"/> instance.</returns>
    public static TestData<T1, T2> CreateTestData<T1, T2>(
        string definition,
        string result,
        T1? arg1, T2? arg2)
    => new(
        definition,
        result,
        arg1, arg2);

    /// <summary>
    /// Creates standard test data with 3 argument(s).
    /// </summary>
    /// <typeparam name="T1">Type of the first test argument.</typeparam>
    /// <typeparam name="T2">Type of the second test argument.</typeparam>
    /// <typeparam name="T3">Type of the third test argument.</typeparam>
    /// <param name="definition">Description of the test scenario.</param>
    /// <param name="result">Expected result description.</param>
    /// <param name="arg1">The first test argument value.</param>
    /// <param name="arg2">The second test argument value.</param>
    /// <param name="arg3">The third test argument value.</param>
    /// <returns>A new <see cref="TestData{T1, T2, T3}"/> instance.</returns>
    public static TestData<T1, T2, T3> CreateTestData<T1, T2, T3>(
        string definition,
        string result,
        T1? arg1, T2? arg2, T3? arg3)
    => new(
        definition,
        result,
        arg1, arg2, arg3);

    /// <summary>
    /// Creates standard test data with 4 argument(s).
    /// </summary>
    /// <typeparam name="T1">Type of the first test argument.</typeparam>
    /// <typeparam name="T2">Type of the second test argument.</typeparam>
    /// <typeparam name="T3">Type of the third test argument.</typeparam>
    /// <typeparam name="T4">Type of the fourth test argument.</typeparam>
    /// <param name="definition">Description of the test scenario.</param>
    /// <param name="result">Expected result description.</param>
    /// <param name="arg1">The first test argument value.</param>
    /// <param name="arg2">The second test argument value.</param>
    /// <param name="arg3">The third test argument value.</param>
    /// <param name="arg4">The fourth test argument value.</param>
    /// <returns>A new <see cref="TestData{T1, T2, T3, T4}"/> instance.</returns>
    public static TestData<T1, T2, T3, T4> CreateTestData<T1, T2, T3, T4>(
        string definition,
        string result,
        T1? arg1, T2? arg2, T3? arg3, T4? arg4)
    => new(
        definition,
        result,
        arg1, arg2, arg3, arg4);

    /// <summary>
    /// Creates standard test data with 5 argument(s).
    /// </summary>
    /// <typeparam name="T1">Type of the first test argument.</typeparam>
    /// <typeparam name="T2">Type of the second test argument.</typeparam>
    /// <typeparam name="T3">Type of the third test argument.</typeparam>
    /// <typeparam name="T4">Type of the fourth test argument.</typeparam>
    /// <typeparam name="T5">Type of the fifth test argument.</typeparam>
    /// <param name="definition">Description of the test scenario.</param>
    /// <param name="result">Expected result description.</param>
    /// <param name="arg1">The first test argument value.</param>
    /// <param name="arg2">The second test argument value.</param>
    /// <param name="arg3">The third test argument value.</param>
    /// <param name="arg4">The fourth test argument value.</param>
    /// <param name="arg5">The fifth test argument value.</param>
    /// <returns>A new <see cref="TestData{T1, T2, T3, T4, T5}"/> instance.</returns>
    public static TestData<T1, T2, T3, T4, T5> CreateTestData<T1, T2, T3, T4, T5>(
        string definition,
        string result,
        T1? arg1, T2? arg2, T3? arg3, T4? arg4, T5? arg5)
    => new(
        definition,
        result,
        arg1, arg2, arg3, arg4, arg5);

    /// <summary>
    /// Creates standard test data with 6 argument(s).
    /// </summary>
    /// <typeparam name="T1">Type of the first test argument.</typeparam>
    /// <typeparam name="T2">Type of the second test argument.</typeparam>
    /// <typeparam name="T3">Type of the third test argument.</typeparam>
    /// <typeparam name="T4">Type of the fourth test argument.</typeparam>
    /// <typeparam name="T5">Type of the fifth test argument.</typeparam>
    /// <typeparam name="T6">Type of the sixth test argument.</typeparam>
    /// <param name="definition">Description of the test scenario.</param>
    /// <param name="result">Expected result description.</param>
    /// <param name="arg1">The first test argument value.</param>
    /// <param name="arg2">The second test argument value.</param>
    /// <param name="arg3">The third test argument value.</param>
    /// <param name="arg4">The fourth test argument value.</param>
    /// <param name="arg5">The fifth test argument value.</param>
    /// <param name="arg6">The sixth test argument value.</param>
    /// <returns>A new <see cref="TestData{T1, T2, T3, T4, T5, T6}"/> instance.</returns>
    public static TestData<T1, T2, T3, T4, T5, T6> CreateTestData<T1, T2, T3, T4, T5, T6>(
        string definition,
        string result,
        T1? arg1, T2? arg2, T3? arg3, T4? arg4, T5? arg5, T6? arg6)
    => new(
        definition,
        result,
        arg1, arg2, arg3, arg4, arg5, arg6);

    /// <summary>
    /// Creates standard test data with 7 argument(s).
    /// </summary>
    /// <typeparam name="T1">Type of the first test argument.</typeparam>
    /// <typeparam name="T2">Type of the second test argument.</typeparam>
    /// <typeparam name="T3">Type of the third test argument.</typeparam>
    /// <typeparam name="T4">Type of the fourth test argument.</typeparam>
    /// <typeparam name="T5">Type of the fifth test argument.</typeparam>
    /// <typeparam name="T6">Type of the sixth test argument.</typeparam>
    /// <typeparam name="T7">Type of the seventh test argument.</typeparam>
    /// <param name="definition">Description of the test scenario.</param>
    /// <param name="result">Expected result description.</param>
    /// <param name="arg1">The first test argument value.</param>
    /// <param name="arg2">The second test argument value.</param>
    /// <param name="arg3">The third test argument value.</param>
    /// <param name="arg4">The fourth test argument value.</param>
    /// <param name="arg5">The fifth test argument value.</param>
    /// <param name="arg6">The sixth test argument value.</param>
    /// <param name="arg7">The seventh test argument value.</param>
    /// <returns>A new <see cref="TestData{T1, T2, T3, T4, T5, T6, T7}"/> instance.</returns>
    public static TestData<T1, T2, T3, T4, T5, T6, T7> CreateTestData<T1, T2, T3, T4, T5, T6, T7>(
        string definition,
        string result,
        T1? arg1, T2? arg2, T3? arg3, T4? arg4, T5? arg5, T6? arg6, T7? arg7)
    => new(
        definition,
        result,
        arg1, arg2, arg3, arg4, arg5, arg6, arg7);

    /// <summary>
    /// Creates standard test data with 8 argument(s).
    /// </summary>
    /// <typeparam name="T1">Type of the first test argument.</typeparam>
    /// <typeparam name="T2">Type of the second test argument.</typeparam>
    /// <typeparam name="T3">Type of the third test argument.</typeparam>
    /// <typeparam name="T4">Type of the fourth test argument.</typeparam>
    /// <typeparam name="T5">Type of the fifth test argument.</typeparam>
    /// <typeparam name="T6">Type of the sixth test argument.</typeparam>
    /// <typeparam name="T7">Type of the seventh test argument.</typeparam>
    /// <typeparam name="T8">Type of the eighth test argument.</typeparam>
    /// <param name="definition">Description of the test scenario.</param>
    /// <param name="result">Expected result description.</param>
    /// <param name="arg1">The first test argument value.</param>
    /// <param name="arg2">The second test argument value.</param>
    /// <param name="arg3">The third test argument value.</param>
    /// <param name="arg4">The fourth test argument value.</param>
    /// <param name="arg5">The fifth test argument value.</param>
    /// <param name="arg6">The sixth test argument value.</param>
    /// <param name="arg7">The seventh test argument value.</param>
    /// <param name="arg8">The eighth test argument value.</param>
    /// <returns>A new <see cref="TestData{T1, T2, T3, T4, T5, T6, T7, T8}"/> instance.</returns>
    public static TestData<T1, T2, T3, T4, T5, T6, T7, T8> CreateTestData<T1, T2, T3, T4, T5, T6, T7, T8>(
        string definition,
        string result,
        T1? arg1, T2? arg2, T3? arg3, T4? arg4, T5? arg5, T6? arg6, T7? arg7, T8? arg8)
    => new(
        definition,
        result,
        arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8);

    /// <summary>
    /// Creates standard test data with 9 argument(s).
    /// </summary>
    /// <typeparam name="T1">Type of the first test argument.</typeparam>
    /// <typeparam name="T2">Type of the second test argument.</typeparam>
    /// <typeparam name="T3">Type of the third test argument.</typeparam>
    /// <typeparam name="T4">Type of the fourth test argument.</typeparam>
    /// <typeparam name="T5">Type of the fifth test argument.</typeparam>
    /// <typeparam name="T6">Type of the sixth test argument.</typeparam>
    /// <typeparam name="T7">Type of the seventh test argument.</typeparam>
    /// <typeparam name="T8">Type of the eighth test argument.</typeparam>
    /// <typeparam name="T9">Type of the ninth test argument.</typeparam>
    /// <param name="definition">Description of the test scenario.</param>
    /// <param name="result">Expected result description.</param>
    /// <param name="arg1">The first test argument value.</param>
    /// <param name="arg2">The second test argument value.</param>
    /// <param name="arg3">The third test argument value.</param>
    /// <param name="arg4">The fourth test argument value.</param>
    /// <param name="arg5">The fifth test argument value.</param>
    /// <param name="arg6">The sixth test argument value.</param>
    /// <param name="arg7">The seventh test argument value.</param>
    /// <param name="arg8">The eighth test argument value.</param>
    /// <param name="arg9">The ninth test argument value.</param>
    /// <returns>A new <see cref="TestData{T1, T2, T3, T4, T5, T6, T7, T8, T9}"/> instance.</returns>
    public static TestData<T1, T2, T3, T4, T5, T6, T7, T8, T9> CreateTestData<T1, T2, T3, T4, T5, T6, T7, T8, T9>(
        string definition,
        string result,
        T1? arg1, T2? arg2, T3? arg3, T4? arg4, T5? arg5, T6? arg6, T7? arg7, T8? arg8, T9? arg9)
    => new(
        definition,
        result,
        arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8, arg9);

    #endregion

    #region CreateTestDataReturns methods
    /// <summary>
    /// Creates test data with an expected return value and 1 argument(s).
    /// </summary>
    /// <typeparam name="TStruct">Type of the expected return value (must be a non-nullable <see cref="ValueType"/>).</typeparam>
    /// <typeparam name="T1">Type of the first test argument.</typeparam>
    /// <param name="definition">Description of the test scenario.</param>
    /// <param name="expected">Expected return value.</param>
    /// <param name="arg1">The first test argument value.</param>
    public static TestDataReturns<TStruct, T1> CreateTestDataReturns<TStruct, T1>(
        string definition,
        TStruct expected,
        T1? arg1)
    where TStruct : struct
    => new(
        definition,
        expected,
        arg1);

    /// <summary>
    /// Creates test data with an expected return value and 2 argument(s).
    /// </summary>
    /// <typeparam name="TStruct">Type of the expected return value (must be a non-nullable <see cref="ValueType"/>).</typeparam>
    /// <typeparam name="T1">Type of the first test argument.</typeparam>
    /// <typeparam name="T2">Type of the second test argument.</typeparam>
    /// <param name="definition">Description of the test scenario.</param>
    /// <param name="expected">Expected return value.</param>
    /// <param name="arg1">The first test argument value.</param>
    /// <param name="arg2">The second test argument value.</param>
    public static TestDataReturns<TStruct, T1, T2> CreateTestDataReturns<TStruct, T1, T2>(
        string definition,
        TStruct expected,
        T1? arg1, T2? arg2)
    where TStruct : struct
    => new(
        definition,
        expected,
        arg1, arg2);

    /// <summary>
    /// Creates test data with an expected return value and 3 argument(s).
    /// </summary>
    /// <typeparam name="TStruct">Type of the expected return value (must be a non-nullable <see cref="ValueType"/>).</typeparam>
    /// <typeparam name="T1">Type of the first test argument.</typeparam>
    /// <typeparam name="T2">Type of the second test argument.</typeparam>
    /// <typeparam name="T3">Type of the third test argument.</typeparam>
    /// <param name="definition">Description of the test scenario.</param>
    /// <param name="expected">Expected return value.</param>
    /// <param name="arg1">The first test argument value.</param>
    /// <param name="arg2">The second test argument value.</param>
    /// <param name="arg3">The third test argument value.</param>
    public static TestDataReturns<TStruct, T1, T2, T3> CreateTestDataReturns<TStruct, T1, T2, T3>(
        string definition,
        TStruct expected,
        T1? arg1, T2? arg2, T3? arg3)
    where TStruct : struct
    => new(
        definition,
        expected,
        arg1, arg2, arg3);

    /// <summary>
    /// Creates test data with an expected return value and 4 argument(s).
    /// </summary>
    /// <typeparam name="TStruct">Type of the expected return value (must be a non-nullable <see cref="ValueType"/>).</typeparam>
    /// <typeparam name="T1">Type of the first test argument.</typeparam>
    /// <typeparam name="T2">Type of the second test argument.</typeparam>
    /// <typeparam name="T3">Type of the third test argument.</typeparam>
    /// <typeparam name="T4">Type of the fourth test argument.</typeparam>
    /// <param name="definition">Description of the test scenario.</param>
    /// <param name="expected">Expected return value.</param>
    /// <param name="arg1">The first test argument value.</param>
    /// <param name="arg2">The second test argument value.</param>
    /// <param name="arg3">The third test argument value.</param>
    /// <param name="arg4">The fourth test argument value.</param>
    public static TestDataReturns<TStruct, T1, T2, T3, T4> CreateTestDataReturns<TStruct, T1, T2, T3, T4>(
        string definition,
        TStruct expected,
        T1? arg1, T2? arg2, T3? arg3, T4? arg4)
    where TStruct : struct
    => new(
        definition,
        expected,
        arg1, arg2, arg3, arg4);

    /// <summary>
    /// Creates test data with an expected return value and 5 argument(s).
    /// </summary>
    /// <typeparam name="TStruct">Type of the expected return value (must be a non-nullable <see cref="ValueType"/>).</typeparam>
    /// <typeparam name="T1">Type of the first test argument.</typeparam>
    /// <typeparam name="T2">Type of the second test argument.</typeparam>
    /// <typeparam name="T3">Type of the third test argument.</typeparam>
    /// <typeparam name="T4">Type of the fourth test argument.</typeparam>
    /// <typeparam name="T5">Type of the fifth test argument.</typeparam>
    /// <param name="definition">Description of the test scenario.</param>
    /// <param name="expected">Expected return value.</param>
    /// <param name="arg1">The first test argument value.</param>
    /// <param name="arg2">The second test argument value.</param>
    /// <param name="arg3">The third test argument value.</param>
    /// <param name="arg4">The fourth test argument value.</param>
    /// <param name="arg5">The fifth test argument value.</param>
    public static TestDataReturns<TStruct, T1, T2, T3, T4, T5> CreateTestDataReturns<TStruct, T1, T2, T3, T4, T5>(
        string definition,
        TStruct expected,
        T1? arg1, T2? arg2, T3? arg3, T4? arg4, T5? arg5)
    where TStruct : struct
    => new(
        definition,
        expected,
        arg1, arg2, arg3, arg4, arg5);

    /// <summary>
    /// Creates test data with an expected return value and 6 argument(s).
    /// </summary>
    /// <typeparam name="TStruct">Type of the expected return value (must be a non-nullable <see cref="ValueType"/>).</typeparam>
    /// <typeparam name="T1">Type of the first test argument.</typeparam>
    /// <typeparam name="T2">Type of the second test argument.</typeparam>
    /// <typeparam name="T3">Type of the third test argument.</typeparam>
    /// <typeparam name="T4">Type of the fourth test argument.</typeparam>
    /// <typeparam name="T5">Type of the fifth test argument.</typeparam>
    /// <typeparam name="T6">Type of the sixth test argument.</typeparam>
    /// <param name="definition">Description of the test scenario.</param>
    /// <param name="expected">Expected return value.</param>
    /// <param name="arg1">The first test argument value.</param>
    /// <param name="arg2">The second test argument value.</param>
    /// <param name="arg3">The third test argument value.</param>
    /// <param name="arg4">The fourth test argument value.</param>
    /// <param name="arg5">The fifth test argument value.</param>
    /// <param name="arg6">The sixth test argument value.</param>
    public static TestDataReturns<TStruct, T1, T2, T3, T4, T5, T6> CreateTestDataReturns<TStruct, T1, T2, T3, T4, T5, T6>(
        string definition,
        TStruct expected,
        T1? arg1, T2? arg2, T3? arg3, T4? arg4, T5? arg5, T6? arg6)
    where TStruct : struct
    => new(
        definition,
        expected,
        arg1, arg2, arg3, arg4, arg5, arg6);

    /// <summary>
    /// Creates test data with an expected return value and 7 argument(s).
    /// </summary>
    /// <typeparam name="TStruct">Type of the expected return value (must be a non-nullable <see cref="ValueType"/>).</typeparam>
    /// <typeparam name="T1">Type of the first test argument.</typeparam>
    /// <typeparam name="T2">Type of the second test argument.</typeparam>
    /// <typeparam name="T3">Type of the third test argument.</typeparam>
    /// <typeparam name="T4">Type of the fourth test argument.</typeparam>
    /// <typeparam name="T5">Type of the fifth test argument.</typeparam>
    /// <typeparam name="T6">Type of the sixth test argument.</typeparam>
    /// <typeparam name="T7">Type of the seventh test argument.</typeparam>
    /// <param name="definition">Description of the test scenario.</param>
    /// <param name="expected">Expected return value.</param>
    /// <param name="arg1">The first test argument value.</param>
    /// <param name="arg2">The second test argument value.</param>
    /// <param name="arg3">The third test argument value.</param>
    /// <param name="arg4">The fourth test argument value.</param>
    /// <param name="arg5">The fifth test argument value.</param>
    /// <param name="arg6">The sixth test argument value.</param>
    /// <param name="arg7">The seventh test argument value.</param>
    public static TestDataReturns<TStruct, T1, T2, T3, T4, T5, T6, T7> CreateTestDataReturns<TStruct, T1, T2, T3, T4, T5, T6, T7>(
        string definition,
        TStruct expected,
        T1? arg1, T2? arg2, T3? arg3, T4? arg4, T5? arg5, T6? arg6, T7? arg7)
    where TStruct : struct
    => new(
        definition,
        expected,
        arg1, arg2, arg3, arg4, arg5, arg6, arg7);

    /// <summary>
    /// Creates test data with an expected return value and 8 argument(s).
    /// </summary>
    /// <typeparam name="TStruct">Type of the expected return value (must be a non-nullable <see cref="ValueType"/>).</typeparam>
    /// <typeparam name="T1">Type of the first test argument.</typeparam>
    /// <typeparam name="T2">Type of the second test argument.</typeparam>
    /// <typeparam name="T3">Type of the third test argument.</typeparam>
    /// <typeparam name="T4">Type of the fourth test argument.</typeparam>
    /// <typeparam name="T5">Type of the fifth test argument.</typeparam>
    /// <typeparam name="T6">Type of the sixth test argument.</typeparam>
    /// <typeparam name="T7">Type of the seventh test argument.</typeparam>
    /// <typeparam name="T8">Type of the eighth test argument.</typeparam>
    /// <param name="definition">Description of the test scenario.</param>
    /// <param name="expected">Expected return value.</param>
    /// <param name="arg1">The first test argument value.</param>
    /// <param name="arg2">The second test argument value.</param>
    /// <param name="arg3">The third test argument value.</param>
    /// <param name="arg4">The fourth test argument value.</param>
    /// <param name="arg5">The fifth test argument value.</param>
    /// <param name="arg6">The sixth test argument value.</param>
    /// <param name="arg7">The seventh test argument value.</param>
    /// <param name="arg8">The eighth test argument value.</param>
    public static TestDataReturns<TStruct, T1, T2, T3, T4, T5, T6, T7, T8> CreateTestDataReturns<TStruct, T1, T2, T3, T4, T5, T6, T7, T8>(
        string definition,
        TStruct expected,
        T1? arg1, T2? arg2, T3? arg3, T4? arg4, T5? arg5, T6? arg6, T7? arg7, T8? arg8)
    where TStruct : struct
    => new(
        definition,
        expected,
        arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8);

    /// <summary>
    /// Creates test data with an expected return value and 9 argument(s).
    /// </summary>
    /// <typeparam name="TStruct">Type of the expected return value (must be a non-nullable <see cref="ValueType"/>).</typeparam>
    /// <typeparam name="T1">Type of the first test argument.</typeparam>
    /// <typeparam name="T2">Type of the second test argument.</typeparam>
    /// <typeparam name="T3">Type of the third test argument.</typeparam>
    /// <typeparam name="T4">Type of the fourth test argument.</typeparam>
    /// <typeparam name="T5">Type of the fifth test argument.</typeparam>
    /// <typeparam name="T6">Type of the sixth test argument.</typeparam>
    /// <typeparam name="T7">Type of the seventh test argument.</typeparam>
    /// <typeparam name="T8">Type of the eighth test argument.</typeparam>
    /// <typeparam name="T9">Type of the ninth test argument.</typeparam>
    /// <param name="definition">Description of the test scenario.</param>
    /// <param name="expected">Expected return value.</param>
    /// <param name="arg1">The first test argument value.</param>
    /// <param name="arg2">The second test argument value.</param>
    /// <param name="arg3">The third test argument value.</param>
    /// <param name="arg4">The fourth test argument value.</param>
    /// <param name="arg5">The fifth test argument value.</param>
    /// <param name="arg6">The sixth test argument value.</param>
    /// <param name="arg7">The seventh test argument value.</param>
    /// <param name="arg8">The eighth test argument value.</param>
    /// <param name="arg9">The ninth test argument value.</param>
    public static TestDataReturns<TStruct, T1, T2, T3, T4, T5, T6, T7, T8, T9> CreateTestDataReturns<TStruct, T1, T2, T3, T4, T5, T6, T7, T8, T9>(
        string definition,
        TStruct expected,
        T1? arg1, T2? arg2, T3? arg3, T4? arg4, T5? arg5, T6? arg6, T7? arg7, T8? arg8, T9? arg9)
    where TStruct : struct
    => new(
        definition,
        expected,
        arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8, arg9);

    #endregion

    #region CreateTestDataThrows methods
    /// <summary>
    /// Creates test data with an expected exception and 1 argument(s).
    /// </summary>
    /// <typeparam name="TException">Type of the expected exception.</typeparam>
    /// <typeparam name="T1">Type of the first test argument.</typeparam>
    /// <param name="definition">Description of the test scenario.</param>
    /// <param name="expected">Expected exception instance.</param>
    /// <param name="arg1">The first test argument value.</param>
    /// <returns>A new <see cref="TestDataThrows{TException, T1}"/> instance.</returns>
    public static TestDataThrows<TException, T1> CreateTestDataThrows<TException, T1>(
        string definition,
        TException expected,
        T1? arg1)
    where TException : Exception
    => new(
        definition,
        expected,
        arg1);

    /// <summary>
    /// Creates test data with an expected exception and 2 argument(s).
    /// </summary>
    /// <typeparam name="TException">Type of the expected exception.</typeparam>
    /// <typeparam name="T1">Type of the first test argument.</typeparam>
    /// <typeparam name="T2">Type of the second test argument.</typeparam>
    /// <param name="definition">Description of the test scenario.</param>
    /// <param name="expected">Expected exception instance.</param>
    /// <param name="arg1">The first test argument value.</param>
    /// <param name="arg2">The second test argument value.</param>
    /// <returns>A new <see cref="TestDataThrows{TException, T1, T2}"/> instance.</returns>
    public static TestDataThrows<TException, T1, T2> CreateTestDataThrows<TException, T1, T2>(
        string definition,
        TException expected,
        T1? arg1, T2? arg2)
    where TException : Exception
    => new(
        definition,
        expected,
        arg1, arg2);

    /// <summary>
    /// Creates test data with an expected exception and 3 argument(s).
    /// </summary>
    /// <typeparam name="TException">Type of the expected exception.</typeparam>
    /// <typeparam name="T1">Type of the first test argument.</typeparam>
    /// <typeparam name="T2">Type of the second test argument.</typeparam>
    /// <typeparam name="T3">Type of the third test argument.</typeparam>
    /// <param name="definition">Description of the test scenario.</param>
    /// <param name="expected">Expected exception instance.</param>
    /// <param name="arg1">The first test argument value.</param>
    /// <param name="arg2">The second test argument value.</param>
    /// <param name="arg3">The third test argument value.</param>
    /// <returns>A new <see cref="TestDataThrows{TException, T1, T2, T3}"/> instance.</returns>
    public static TestDataThrows<TException, T1, T2, T3> CreateTestDataThrows<TException, T1, T2, T3>(
        string definition,
        TException expected,
        T1? arg1, T2? arg2, T3? arg3)
    where TException : Exception
    => new(
        definition,
        expected,
        arg1, arg2, arg3);

    /// <summary>
    /// Creates test data with an expected exception and 4 argument(s).
    /// </summary>
    /// <typeparam name="TException">Type of the expected exception.</typeparam>
    /// <typeparam name="T1">Type of the first test argument.</typeparam>
    /// <typeparam name="T2">Type of the second test argument.</typeparam>
    /// <typeparam name="T3">Type of the third test argument.</typeparam>
    /// <typeparam name="T4">Type of the fourth test argument.</typeparam>
    /// <param name="definition">Description of the test scenario.</param>
    /// <param name="expected">Expected exception instance.</param>
    /// <param name="arg1">The first test argument value.</param>
    /// <param name="arg2">The second test argument value.</param>
    /// <param name="arg3">The third test argument value.</param>
    /// <param name="arg4">The fourth test argument value.</param>
    /// <returns>A new <see cref="TestDataThrows{TException, T1, T2, T3, T4}"/> instance.</returns>
    public static TestDataThrows<TException, T1, T2, T3, T4> CreateTestDataThrows<TException, T1, T2, T3, T4>(
        string definition,
        TException expected,
        T1? arg1, T2? arg2, T3? arg3, T4? arg4)
    where TException : Exception
    => new(
        definition,
        expected,
        arg1, arg2, arg3, arg4);

    /// <summary>
    /// Creates test data with an expected exception and 5 argument(s).
    /// </summary>
    /// <typeparam name="TException">Type of the expected exception.</typeparam>
    /// <typeparam name="T1">Type of the first test argument.</typeparam>
    /// <typeparam name="T2">Type of the second test argument.</typeparam>
    /// <typeparam name="T3">Type of the third test argument.</typeparam>
    /// <typeparam name="T4">Type of the fourth test argument.</typeparam>
    /// <typeparam name="T5">Type of the fifth test argument.</typeparam>
    /// <param name="definition">Description of the test scenario.</param>
    /// <param name="expected">Expected exception instance.</param>
    /// <param name="arg1">The first test argument value.</param>
    /// <param name="arg2">The second test argument value.</param>
    /// <param name="arg3">The third test argument value.</param>
    /// <param name="arg4">The fourth test argument value.</param>
    /// <param name="arg5">The fifth test argument value.</param>
    /// <returns>A new <see cref="TestDataThrows{TException, T1, T2, T3, T4, T5}"/> instance.</returns>
    public static TestDataThrows<TException, T1, T2, T3, T4, T5> CreateTestDataThrows<TException, T1, T2, T3, T4, T5>(
        string definition,
        TException expected,
        T1? arg1, T2? arg2, T3? arg3, T4? arg4, T5? arg5)
    where TException : Exception
    => new(
        definition,
        expected,
        arg1, arg2, arg3, arg4, arg5);

    /// <summary>
    /// Creates test data with an expected exception and 6 argument(s).
    /// </summary>
    /// <typeparam name="TException">Type of the expected exception.</typeparam>
    /// <typeparam name="T1">Type of the first test argument.</typeparam>
    /// <typeparam name="T2">Type of the second test argument.</typeparam>
    /// <typeparam name="T3">Type of the third test argument.</typeparam>
    /// <typeparam name="T4">Type of the fourth test argument.</typeparam>
    /// <typeparam name="T5">Type of the fifth test argument.</typeparam>
    /// <typeparam name="T6">Type of the sixth test argument.</typeparam>
    /// <param name="definition">Description of the test scenario.</param>
    /// <param name="expected">Expected exception instance.</param>
    /// <param name="arg1">The first test argument value.</param>
    /// <param name="arg2">The second test argument value.</param>
    /// <param name="arg3">The third test argument value.</param>
    /// <param name="arg4">The fourth test argument value.</param>
    /// <param name="arg5">The fifth test argument value.</param>
    /// <param name="arg6">The sixth test argument value.</param>
    /// <returns>A new <see cref="TestDataThrows{TException, T1, T2, T3, T4, T5, T6}"/> instance.</returns>
    public static TestDataThrows<TException, T1, T2, T3, T4, T5, T6> CreateTestDataThrows<TException, T1, T2, T3, T4, T5, T6>(
        string definition,
        TException expected,
        T1? arg1, T2? arg2, T3? arg3, T4? arg4, T5? arg5, T6? arg6)
    where TException : Exception
    => new(
        definition,
        expected,
        arg1, arg2, arg3, arg4, arg5, arg6);

    /// <summary>
    /// Creates test data with an expected exception and 7 argument(s).
    /// </summary>
    /// <typeparam name="TException">Type of the expected exception.</typeparam>
    /// <typeparam name="T1">Type of the first test argument.</typeparam>
    /// <typeparam name="T2">Type of the second test argument.</typeparam>
    /// <typeparam name="T3">Type of the third test argument.</typeparam>
    /// <typeparam name="T4">Type of the fourth test argument.</typeparam>
    /// <typeparam name="T5">Type of the fifth test argument.</typeparam>
    /// <typeparam name="T6">Type of the sixth test argument.</typeparam>
    /// <typeparam name="T7">Type of the seventh test argument.</typeparam>
    /// <param name="definition">Description of the test scenario.</param>
    /// <param name="expected">Expected exception instance.</param>
    /// <param name="arg1">The first test argument value.</param>
    /// <param name="arg2">The second test argument value.</param>
    /// <param name="arg3">The third test argument value.</param>
    /// <param name="arg4">The fourth test argument value.</param>
    /// <param name="arg5">The fifth test argument value.</param>
    /// <param name="arg6">The sixth test argument value.</param>
    /// <param name="arg7">The seventh test argument value.</param>
    /// <returns>A new <see cref="TestDataThrows{TException, T1, T2, T3, T4, T5, T6, T7}"/> instance.</returns>
    public static TestDataThrows<TException, T1, T2, T3, T4, T5, T6, T7> CreateTestDataThrows<TException, T1, T2, T3, T4, T5, T6, T7>(
        string definition,
        TException expected,
        T1? arg1, T2? arg2, T3? arg3, T4? arg4, T5? arg5, T6? arg6, T7? arg7)
    where TException : Exception
    => new(
        definition,
        expected,
        arg1, arg2, arg3, arg4, arg5, arg6, arg7);

    /// <summary>
    /// Creates test data with an expected exception and 8 argument(s).
    /// </summary>
    /// <typeparam name="TException">Type of the expected exception.</typeparam>
    /// <typeparam name="T1">Type of the first test argument.</typeparam>
    /// <typeparam name="T2">Type of the second test argument.</typeparam>
    /// <typeparam name="T3">Type of the third test argument.</typeparam>
    /// <typeparam name="T4">Type of the fourth test argument.</typeparam>
    /// <typeparam name="T5">Type of the fifth test argument.</typeparam>
    /// <typeparam name="T6">Type of the sixth test argument.</typeparam>
    /// <typeparam name="T7">Type of the seventh test argument.</typeparam>
    /// <typeparam name="T8">Type of the eighth test argument.</typeparam>
    /// <param name="definition">Description of the test scenario.</param>
    /// <param name="expected">Expected exception instance.</param>
    /// <param name="arg1">The first test argument value.</param>
    /// <param name="arg2">The second test argument value.</param>
    /// <param name="arg3">The third test argument value.</param>
    /// <param name="arg4">The fourth test argument value.</param>
    /// <param name="arg5">The fifth test argument value.</param>
    /// <param name="arg6">The sixth test argument value.</param>
    /// <param name="arg7">The seventh test argument value.</param>
    /// <param name="arg8">The eighth test argument value.</param>
    /// <returns>A new <see cref="TestDataThrows{TException, T1, T2, T3, T4, T5, T6, T7, T8}"/> instance.</returns>
    public static TestDataThrows<TException, T1, T2, T3, T4, T5, T6, T7, T8> CreateTestDataThrows<TException, T1, T2, T3, T4, T5, T6, T7, T8>(
        string definition,
        TException expected,
        T1? arg1, T2? arg2, T3? arg3, T4? arg4, T5? arg5, T6? arg6, T7? arg7, T8? arg8)
    where TException : Exception
    => new(
        definition,
        expected,
        arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8);

    /// <summary>
    /// Creates test data with an expected exception and 9 argument(s).
    /// </summary>
    /// <typeparam name="TException">Type of the expected exception.</typeparam>
    /// <typeparam name="T1">Type of the first test argument.</typeparam>
    /// <typeparam name="T2">Type of the second test argument.</typeparam>
    /// <typeparam name="T3">Type of the third test argument.</typeparam>
    /// <typeparam name="T4">Type of the fourth test argument.</typeparam>
    /// <typeparam name="T5">Type of the fifth test argument.</typeparam>
    /// <typeparam name="T6">Type of the sixth test argument.</typeparam>
    /// <typeparam name="T7">Type of the seventh test argument.</typeparam>
    /// <typeparam name="T8">Type of the eighth test argument.</typeparam>
    /// <typeparam name="T9">Type of the ninth test argument.</typeparam>
    /// <param name="definition">Description of the test scenario.</param>
    /// <param name="expected">Expected exception instance.</param>
    /// <param name="arg1">The first test argument value.</param>
    /// <param name="arg2">The second test argument value.</param>
    /// <param name="arg3">The third test argument value.</param>
    /// <param name="arg4">The fourth test argument value.</param>
    /// <param name="arg5">The fifth test argument value.</param>
    /// <param name="arg6">The sixth test argument value.</param>
    /// <param name="arg7">The seventh test argument value.</param>
    /// <param name="arg8">The eighth test argument value.</param>
    /// <param name="arg9">The ninth test argument value.</param>
    /// <returns>A new <see cref="TestDataThrows{TException, T1, T2, T3, T4, T5, T6, T7, T8, T9}"/> instance.</returns>
    public static TestDataThrows<TException, T1, T2, T3, T4, T5, T6, T7, T8, T9> CreateTestDataThrows<TException, T1, T2, T3, T4, T5, T6, T7, T8, T9>(
        string definition,
        TException expected,
        T1? arg1, T2? arg2, T3? arg3, T4? arg4, T5? arg5, T6? arg6, T7? arg7, T8? arg8, T9? arg9)
    where TException : Exception
    => new(
        definition,
        expected,
        arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8, arg9);

    #endregion
}
