// <auto-generated>
// This file was generated by a T4 template. Do not modify directly.
// Edit TestData.tt instead.
// </auto-generated>
// SPDX-License-Identifier: MIT
// Copyright (c) 2026. Csaba Dudas (CsabaDu)

#nullable enable

using Portamical.Core.Strategy;

namespace Portamical.Core.TestDataTypes.Models.General;

#region Concrete types
/// <summary>
/// Represents a general purpose strongly typed test data with 1 argument(s).
/// </summary>
/// <typeparam name="T1">The type of the first test argument.</typeparam>
public class TestData<T1>
: TestData
{
    internal TestData(
        string definition,
        string result,
        T1? arg1)
    : base(definition, result)
    {
        Arg1 = arg1;
    }

    /// <summary>
    /// Gets the first test argument value.
    /// </summary>
    public T1? Arg1 { get; init; }

    /// <inheritdoc/>
    protected override object?[] ToObjectArray(ArgsCode argsCode)
    => Extend(base.ToObjectArray, argsCode, Arg1);
}

/// <summary>
/// Represents a general purpose strongly typed test data with 2 argument(s).
/// </summary>
/// <typeparam name="T1">The type of the first test argument.</typeparam>
/// <typeparam name="T2">The type of the second test argument.</typeparam>
public class TestData<T1, T2>
: TestData<T1>
{
    internal TestData(
        string definition,
        string result,
        T1? arg1, T2? arg2)
    : base(definition, result, arg1)
    {
        Arg2 = arg2;
    }

    /// <summary>
    /// Gets the second test argument value.
    /// </summary>
    public T2? Arg2 { get; init; }

    /// <inheritdoc/>
    protected override object?[] ToObjectArray(ArgsCode argsCode)
    => Extend(base.ToObjectArray, argsCode, Arg2);
}

/// <summary>
/// Represents a general purpose strongly typed test data with 3 argument(s).
/// </summary>
/// <typeparam name="T1">The type of the first test argument.</typeparam>
/// <typeparam name="T2">The type of the second test argument.</typeparam>
/// <typeparam name="T3">The type of the third test argument.</typeparam>
public class TestData<T1, T2, T3>
: TestData<T1, T2>
{
    internal TestData(
        string definition,
        string result,
        T1? arg1, T2? arg2, T3? arg3)
    : base(definition, result, arg1, arg2)
    {
        Arg3 = arg3;
    }

    /// <summary>
    /// Gets the third test argument value.
    /// </summary>
    public T3? Arg3 { get; init; }

    /// <inheritdoc/>
    protected override object?[] ToObjectArray(ArgsCode argsCode)
    => Extend(base.ToObjectArray, argsCode, Arg3);
}

/// <summary>
/// Represents a general purpose strongly typed test data with 4 argument(s).
/// </summary>
/// <typeparam name="T1">The type of the first test argument.</typeparam>
/// <typeparam name="T2">The type of the second test argument.</typeparam>
/// <typeparam name="T3">The type of the third test argument.</typeparam>
/// <typeparam name="T4">The type of the fourth test argument.</typeparam>
public class TestData<T1, T2, T3, T4>
: TestData<T1, T2, T3>
{
    internal TestData(
        string definition,
        string result,
        T1? arg1, T2? arg2, T3? arg3, T4? arg4)
    : base(definition, result, arg1, arg2, arg3)
    {
        Arg4 = arg4;
    }

    /// <summary>
    /// Gets the fourth test argument value.
    /// </summary>
    public T4? Arg4 { get; init; }

    /// <inheritdoc/>
    protected override object?[] ToObjectArray(ArgsCode argsCode)
    => Extend(base.ToObjectArray, argsCode, Arg4);
}

/// <summary>
/// Represents a general purpose strongly typed test data with 5 argument(s).
/// </summary>
/// <typeparam name="T1">The type of the first test argument.</typeparam>
/// <typeparam name="T2">The type of the second test argument.</typeparam>
/// <typeparam name="T3">The type of the third test argument.</typeparam>
/// <typeparam name="T4">The type of the fourth test argument.</typeparam>
/// <typeparam name="T5">The type of the fifth test argument.</typeparam>
public class TestData<T1, T2, T3, T4, T5>
: TestData<T1, T2, T3, T4>
{
    internal TestData(
        string definition,
        string result,
        T1? arg1, T2? arg2, T3? arg3, T4? arg4, T5? arg5)
    : base(definition, result, arg1, arg2, arg3, arg4)
    {
        Arg5 = arg5;
    }

    /// <summary>
    /// Gets the fifth test argument value.
    /// </summary>
    public T5? Arg5 { get; init; }

    /// <inheritdoc/>
    protected override object?[] ToObjectArray(ArgsCode argsCode)
    => Extend(base.ToObjectArray, argsCode, Arg5);
}

/// <summary>
/// Represents a general purpose strongly typed test data with 6 argument(s).
/// </summary>
/// <typeparam name="T1">The type of the first test argument.</typeparam>
/// <typeparam name="T2">The type of the second test argument.</typeparam>
/// <typeparam name="T3">The type of the third test argument.</typeparam>
/// <typeparam name="T4">The type of the fourth test argument.</typeparam>
/// <typeparam name="T5">The type of the fifth test argument.</typeparam>
/// <typeparam name="T6">The type of the sixth test argument.</typeparam>
public class TestData<T1, T2, T3, T4, T5, T6>
: TestData<T1, T2, T3, T4, T5>
{
    internal TestData(
        string definition,
        string result,
        T1? arg1, T2? arg2, T3? arg3, T4? arg4, T5? arg5, T6? arg6)
    : base(definition, result, arg1, arg2, arg3, arg4, arg5)
    {
        Arg6 = arg6;
    }

    /// <summary>
    /// Gets the sixth test argument value.
    /// </summary>
    public T6? Arg6 { get; init; }

    /// <inheritdoc/>
    protected override object?[] ToObjectArray(ArgsCode argsCode)
    => Extend(base.ToObjectArray, argsCode, Arg6);
}

/// <summary>
/// Represents a general purpose strongly typed test data with 7 argument(s).
/// </summary>
/// <typeparam name="T1">The type of the first test argument.</typeparam>
/// <typeparam name="T2">The type of the second test argument.</typeparam>
/// <typeparam name="T3">The type of the third test argument.</typeparam>
/// <typeparam name="T4">The type of the fourth test argument.</typeparam>
/// <typeparam name="T5">The type of the fifth test argument.</typeparam>
/// <typeparam name="T6">The type of the sixth test argument.</typeparam>
/// <typeparam name="T7">The type of the seventh test argument.</typeparam>
public class TestData<T1, T2, T3, T4, T5, T6, T7>
: TestData<T1, T2, T3, T4, T5, T6>
{
    internal TestData(
        string definition,
        string result,
        T1? arg1, T2? arg2, T3? arg3, T4? arg4, T5? arg5, T6? arg6, T7? arg7)
    : base(definition, result, arg1, arg2, arg3, arg4, arg5, arg6)
    {
        Arg7 = arg7;
    }

    /// <summary>
    /// Gets the seventh test argument value.
    /// </summary>
    public T7? Arg7 { get; init; }

    /// <inheritdoc/>
    protected override object?[] ToObjectArray(ArgsCode argsCode)
    => Extend(base.ToObjectArray, argsCode, Arg7);
}

/// <summary>
/// Represents a general purpose strongly typed test data with 8 argument(s).
/// </summary>
/// <typeparam name="T1">The type of the first test argument.</typeparam>
/// <typeparam name="T2">The type of the second test argument.</typeparam>
/// <typeparam name="T3">The type of the third test argument.</typeparam>
/// <typeparam name="T4">The type of the fourth test argument.</typeparam>
/// <typeparam name="T5">The type of the fifth test argument.</typeparam>
/// <typeparam name="T6">The type of the sixth test argument.</typeparam>
/// <typeparam name="T7">The type of the seventh test argument.</typeparam>
/// <typeparam name="T8">The type of the eighth test argument.</typeparam>
public class TestData<T1, T2, T3, T4, T5, T6, T7, T8>
: TestData<T1, T2, T3, T4, T5, T6, T7>
{
    internal TestData(
        string definition,
        string result,
        T1? arg1, T2? arg2, T3? arg3, T4? arg4, T5? arg5, T6? arg6, T7? arg7, T8? arg8)
    : base(definition, result, arg1, arg2, arg3, arg4, arg5, arg6, arg7)
    {
        Arg8 = arg8;
    }

    /// <summary>
    /// Gets the eighth test argument value.
    /// </summary>
    public T8? Arg8 { get; init; }

    /// <inheritdoc/>
    protected override object?[] ToObjectArray(ArgsCode argsCode)
    => Extend(base.ToObjectArray, argsCode, Arg8);
}

/// <summary>
/// Represents a general purpose strongly typed test data with 9 argument(s).
/// </summary>
/// <typeparam name="T1">The type of the first test argument.</typeparam>
/// <typeparam name="T2">The type of the second test argument.</typeparam>
/// <typeparam name="T3">The type of the third test argument.</typeparam>
/// <typeparam name="T4">The type of the fourth test argument.</typeparam>
/// <typeparam name="T5">The type of the fifth test argument.</typeparam>
/// <typeparam name="T6">The type of the sixth test argument.</typeparam>
/// <typeparam name="T7">The type of the seventh test argument.</typeparam>
/// <typeparam name="T8">The type of the eighth test argument.</typeparam>
/// <typeparam name="T9">The type of the ninth test argument.</typeparam>
public class TestData<T1, T2, T3, T4, T5, T6, T7, T8, T9>
: TestData<T1, T2, T3, T4, T5, T6, T7, T8>
{
    internal TestData(
        string definition,
        string result,
        T1? arg1, T2? arg2, T3? arg3, T4? arg4, T5? arg5, T6? arg6, T7? arg7, T8? arg8, T9? arg9)
    : base(definition, result, arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8)
    {
        Arg9 = arg9;
    }

    /// <summary>
    /// Gets the ninth test argument value.
    /// </summary>
    public T9? Arg9 { get; init; }

    /// <inheritdoc/>
    protected override object?[] ToObjectArray(ArgsCode argsCode)
    => Extend(base.ToObjectArray, argsCode, Arg9);
}

#endregion
