// SPDX-License-Identifier: MIT
// Copyright (c) 2026. Csaba Dudas (CsabaDu)

// Tests for the 9 TestDataReturns<TStruct,T1..T9> classes generated by TestDataReturns.tt.
// Verifies T4 template contracts: MaxArity=9, TypeParams, ArgsList, BaseArgsList.
// Domain behaviour (TestCaseName, GetResult, ToArgs) is tested in TestDataTypes\.

using Portamical.Core.Factories;
using Portamical.Core.TestDataTypes.Models.Specialized;

namespace Tests.Portamical.Core.T4;

[TestClass]
public class TestDataReturnsGeneratedTests
{
    private const string Def = "definition";
    private const int Expected = 5;

    #region MaxArity = 9
    [TestMethod]
    public void MaxArity_allNineOverloads_canBeCreated()
    {
        Assert.IsNotNull(TestDataFactory.CreateTestDataReturns<int, int>(Def, Expected, 1));
        Assert.IsNotNull(TestDataFactory.CreateTestDataReturns<int, int, int>(Def, Expected, 1, 2));
        Assert.IsNotNull(TestDataFactory.CreateTestDataReturns<int, int, int, int>(Def, Expected, 1, 2, 3));
        Assert.IsNotNull(TestDataFactory.CreateTestDataReturns<int, int, int, int, int>(Def, Expected, 1, 2, 3, 4));
        Assert.IsNotNull(TestDataFactory.CreateTestDataReturns<int, int, int, int, int, int>(Def, Expected, 1, 2, 3, 4, 5));
        Assert.IsNotNull(TestDataFactory.CreateTestDataReturns<int, int, int, int, int, int, int>(Def, Expected, 1, 2, 3, 4, 5, 6));
        Assert.IsNotNull(TestDataFactory.CreateTestDataReturns<int, int, int, int, int, int, int, int>(Def, Expected, 1, 2, 3, 4, 5, 6, 7));
        Assert.IsNotNull(TestDataFactory.CreateTestDataReturns<int, int, int, int, int, int, int, int, int>(Def, Expected, 1, 2, 3, 4, 5, 6, 7, 8));
        Assert.IsNotNull(TestDataFactory.CreateTestDataReturns<int, int, int, int, int, int, int, int, int, int>(Def, Expected, 1, 2, 3, 4, 5, 6, 7, 8, 9));
    }
    #endregion

    #region TypeParams (correct concrete generic type per arity)
    [TestMethod]
    public void Arity1_isInstanceOf_testDataReturnsStructT1()
    {
        var sut = TestDataFactory.CreateTestDataReturns<int, int>(Def, Expected, 1);
        Assert.IsInstanceOfType<TestDataReturns<int, int>>(sut);
    }

    [TestMethod]
    public void Arity9_isInstanceOf_testDataReturnsStructT1ToT9()
    {
        var sut = TestDataFactory.CreateTestDataReturns<int, int, int, int, int, int, int, int, int, int>(
            Def, Expected, 1, 2, 3, 4, 5, 6, 7, 8, 9);
        Assert.IsInstanceOfType<TestDataReturns<int, int, int, int, int, int, int, int, int, int>>(sut);
    }
    #endregion

    #region ArgsList (each ArgN property stores its corresponding constructor argument)
    [TestMethod]
    public void Arity9_expectedAndAllArgNProperties_haveExpectedValues()
    {
        var sut = TestDataFactory.CreateTestDataReturns<int, int, int, int, int, int, int, int, int, int>(
            Def, Expected, 1, 2, 3, 4, 5, 6, 7, 8, 9);

        Assert.AreEqual(Expected, sut.Expected);
        Assert.AreEqual(1, sut.Arg1);
        Assert.AreEqual(2, sut.Arg2);
        Assert.AreEqual(3, sut.Arg3);
        Assert.AreEqual(4, sut.Arg4);
        Assert.AreEqual(5, sut.Arg5);
        Assert.AreEqual(6, sut.Arg6);
        Assert.AreEqual(7, sut.Arg7);
        Assert.AreEqual(8, sut.Arg8);
        Assert.AreEqual(9, sut.Arg9);
    }
    #endregion

    #region BaseArgsList (each class passes prior args to its base class constructor)
    [TestMethod]
    public void Arity2_isInstanceOf_arity1()
    {
        var sut = TestDataFactory.CreateTestDataReturns<int, string, bool>(Def, Expected, "a", true);
        Assert.IsInstanceOfType<TestDataReturns<int, string>>(sut);
    }

    [TestMethod]
    public void Arity2_arg1_isAccessibleFromBaseClass()
    {
        var sut = TestDataFactory.CreateTestDataReturns<int, string, bool>(Def, Expected, "hello", true);
        Assert.AreEqual("hello", sut.Arg1);    // Arg1 lives on TestDataReturns<TStruct, T1> (base)
        Assert.IsTrue(sut.Arg2);
    }

    [TestMethod]
    public void Arity9_isInstanceOf_arity1()
    {
        var sut = TestDataFactory.CreateTestDataReturns<int, int, int, int, int, int, int, int, int, int>(
            Def, Expected, 1, 2, 3, 4, 5, 6, 7, 8, 9);
        Assert.IsInstanceOfType<TestDataReturns<int, int>>(sut);
    }
    #endregion

}
