// SPDX-License-Identifier: MIT
// Copyright (c) 2026. Csaba Dudas (CsabaDu)

// Tests for the 9 TestDataThrows<TException,T1..T9> classes generated by TestDataThrows.tt.
// Verifies T4 template contracts: MaxArity=9, TypeParams, ArgsList, BaseArgsList,
// Expected property, GetResult format, and PropsCode-based trimming.

using Portamical.Core.Factories;
using Portamical.Core.Strategy;
using Portamical.Core.TestDataTypes.Models.Specialized;

namespace Tests.Portamical.Core.T4;

[TestClass]
public class TestDataThrowsGeneratedTests
{
    private const string Def = "definition";
    private static readonly InvalidOperationException Expected = new();

    #region MaxArity = 9
    [TestMethod]
    public void maxArity_allNineOverloads_canBeCreated()
    {
        Assert.IsNotNull(TestDataFactory.CreateTestDataThrows<InvalidOperationException, int>(Def, Expected, 1));
        Assert.IsNotNull(TestDataFactory.CreateTestDataThrows<InvalidOperationException, int, int>(Def, Expected, 1, 2));
        Assert.IsNotNull(TestDataFactory.CreateTestDataThrows<InvalidOperationException, int, int, int>(Def, Expected, 1, 2, 3));
        Assert.IsNotNull(TestDataFactory.CreateTestDataThrows<InvalidOperationException, int, int, int, int>(Def, Expected, 1, 2, 3, 4));
        Assert.IsNotNull(TestDataFactory.CreateTestDataThrows<InvalidOperationException, int, int, int, int, int>(Def, Expected, 1, 2, 3, 4, 5));
        Assert.IsNotNull(TestDataFactory.CreateTestDataThrows<InvalidOperationException, int, int, int, int, int, int>(Def, Expected, 1, 2, 3, 4, 5, 6));
        Assert.IsNotNull(TestDataFactory.CreateTestDataThrows<InvalidOperationException, int, int, int, int, int, int, int>(Def, Expected, 1, 2, 3, 4, 5, 6, 7));
        Assert.IsNotNull(TestDataFactory.CreateTestDataThrows<InvalidOperationException, int, int, int, int, int, int, int, int>(Def, Expected, 1, 2, 3, 4, 5, 6, 7, 8));
        Assert.IsNotNull(TestDataFactory.CreateTestDataThrows<InvalidOperationException, int, int, int, int, int, int, int, int, int>(Def, Expected, 1, 2, 3, 4, 5, 6, 7, 8, 9));
    }
    #endregion

    #region TypeParams (correct concrete generic type per arity)
    [TestMethod]
    public void arity1_isInstanceOf_testDataThrowsExceptionT1()
    {
        var sut = TestDataFactory.CreateTestDataThrows<InvalidOperationException, int>(Def, Expected, 1);
        Assert.IsInstanceOfType<TestDataThrows<InvalidOperationException, int>>(sut);
    }

    [TestMethod]
    public void arity9_isInstanceOf_testDataThrowsExceptionT1ToT9()
    {
        var sut = TestDataFactory.CreateTestDataThrows<InvalidOperationException, int, int, int, int, int, int, int, int, int>(
            Def, Expected, 1, 2, 3, 4, 5, 6, 7, 8, 9);
        Assert.IsInstanceOfType<TestDataThrows<InvalidOperationException, int, int, int, int, int, int, int, int, int>>(sut);
    }
    #endregion

    #region ArgsList (each ArgN property stores its corresponding constructor argument)
    [TestMethod]
    public void arity9_expectedAndAllArgNProperties_haveExpectedValues()
    {
        var sut = TestDataFactory.CreateTestDataThrows<InvalidOperationException, int, int, int, int, int, int, int, int, int>(
            Def, Expected, 1, 2, 3, 4, 5, 6, 7, 8, 9);

        Assert.AreSame(Expected, sut.Expected);
        Assert.AreEqual(1, sut.Arg1);
        Assert.AreEqual(2, sut.Arg2);
        Assert.AreEqual(3, sut.Arg3);
        Assert.AreEqual(4, sut.Arg4);
        Assert.AreEqual(5, sut.Arg5);
        Assert.AreEqual(6, sut.Arg6);
        Assert.AreEqual(7, sut.Arg7);
        Assert.AreEqual(8, sut.Arg8);
        Assert.AreEqual(9, sut.Arg9);
    }
    #endregion

    #region BaseArgsList (each class passes prior args to its base class constructor)
    [TestMethod]
    public void arity2_isInstanceOf_arity1()
    {
        var sut = TestDataFactory.CreateTestDataThrows<InvalidOperationException, string, bool>(Def, Expected, "a", true);
        Assert.IsInstanceOfType<TestDataThrows<InvalidOperationException, string>>(sut);
    }

    [TestMethod]
    public void arity2_arg1_isAccessibleFromBaseClass()
    {
        var sut = TestDataFactory.CreateTestDataThrows<InvalidOperationException, string, bool>(Def, Expected, "hello", true);
        Assert.AreEqual("hello", sut.Arg1);    // Arg1 lives on TestDataThrows<TException, T1> (base)
        Assert.IsTrue(sut.Arg2);
    }

    [TestMethod]
    public void arity9_isInstanceOf_arity1()
    {
        var sut = TestDataFactory.CreateTestDataThrows<InvalidOperationException, int, int, int, int, int, int, int, int, int>(
            Def, Expected, 1, 2, 3, 4, 5, 6, 7, 8, 9);
        Assert.IsInstanceOfType<TestDataThrows<InvalidOperationException, int>>(sut);
    }
    #endregion

    #region TestCaseName and GetResult
    [TestMethod]
    public void getResult_hasFormat_throwsExceptionTypeName()
    {
        var sut = TestDataFactory.CreateTestDataThrows<InvalidOperationException, int>(Def, Expected, 1);
        Assert.AreEqual($"throws {nameof(InvalidOperationException)}", sut.GetResult());
    }

    [TestMethod]
    public void testCaseName_hasFormat_definitionArrowThrowsExceptionTypeName()
    {
        var sut = TestDataFactory.CreateTestDataThrows<InvalidOperationException, int>(Def, Expected, 1);
        Assert.AreEqual($"{Def} => throws {nameof(InvalidOperationException)}", sut.TestCaseName);
    }
    #endregion

    #region ToArgs
    [TestMethod]
    public void toArgs_instance_returnsSingleElementArray_containingInstance()
    {
        var sut = TestDataFactory.CreateTestDataThrows<InvalidOperationException, int>(Def, Expected, 1);
        var args = sut.ToArgs(ArgsCode.Instance, PropsCode.All);
        Assert.HasCount(1, args);
        Assert.AreSame(sut, args[0]);
    }

    [TestMethod]
    public void toArgs_properties_all_returnsTestCaseName_expected_andArg1()
    {
        var sut = TestDataFactory.CreateTestDataThrows<InvalidOperationException, int>(Def, Expected, 42);
        var args = sut.ToArgs(ArgsCode.Properties, PropsCode.All);
        Assert.HasCount(3, args);
        Assert.AreEqual(sut.TestCaseName, args[0]);
        Assert.AreSame(Expected, args[1]);
        Assert.AreEqual(42, args[2]);
    }

    [TestMethod]
    public void toArgs_properties_trimTestCaseName_returnsExpected_andArg1()
    {
        var sut = TestDataFactory.CreateTestDataThrows<InvalidOperationException, int>(Def, Expected, 42);
        var args = sut.ToArgs(ArgsCode.Properties, PropsCode.TrimTestCaseName);
        Assert.HasCount(2, args);
        Assert.AreSame(Expected, args[0]);
        Assert.AreEqual(42, args[1]);
    }

    [TestMethod]
    public void toArgs_properties_trimThrowsExpected_removesTestCaseName_andExpected()
    {
        var sut = TestDataFactory.CreateTestDataThrows<InvalidOperationException, int>(Def, Expected, 42);
        var args = sut.ToArgs(ArgsCode.Properties, PropsCode.TrimThrowsExpected);
        Assert.HasCount(1, args);
        Assert.AreEqual(42, args[0]);
    }

    [TestMethod]
    public void toArgs_properties_trimReturnsExpected_leavesExpected_inArray()
    {
        // TrimReturnsExpected is not the trim code for TestDataThrows;
        // it trims only TestCaseName (same result as TrimTestCaseName).
        var sut = TestDataFactory.CreateTestDataThrows<InvalidOperationException, int>(Def, Expected, 42);
        var args = sut.ToArgs(ArgsCode.Properties, PropsCode.TrimReturnsExpected);
        Assert.HasCount(2, args);
        Assert.AreSame(Expected, args[0]);
        Assert.AreEqual(42, args[1]);
    }
    #endregion
}
