// SPDX-License-Identifier: MIT
// Copyright (c) 2026. Csaba Dudas (CsabaDu)

// Tests for the 9 TestData<T1..T9> classes generated by TestData.tt.
// Verifies T4 template contracts: MaxArity=9, TypeParams, ArgsList, BaseArgsList.

using Portamical.Core.Factories;
using Portamical.Core.Strategy;
using Portamical.Core.TestDataTypes.Models.General;

namespace Tests.Portamical.Core.T4;

[TestClass]
public class TestDataGeneratedTests
{
    private const string Def = "definition";
    private const string Result = "result";

    #region MaxArity = 9
    [TestMethod]
    public void maxArity_allNineOverloads_canBeCreated()
    {
        Assert.IsNotNull(TestDataFactory.CreateTestData<int>(Def, Result, 1));
        Assert.IsNotNull(TestDataFactory.CreateTestData<int, int>(Def, Result, 1, 2));
        Assert.IsNotNull(TestDataFactory.CreateTestData<int, int, int>(Def, Result, 1, 2, 3));
        Assert.IsNotNull(TestDataFactory.CreateTestData<int, int, int, int>(Def, Result, 1, 2, 3, 4));
        Assert.IsNotNull(TestDataFactory.CreateTestData<int, int, int, int, int>(Def, Result, 1, 2, 3, 4, 5));
        Assert.IsNotNull(TestDataFactory.CreateTestData<int, int, int, int, int, int>(Def, Result, 1, 2, 3, 4, 5, 6));
        Assert.IsNotNull(TestDataFactory.CreateTestData<int, int, int, int, int, int, int>(Def, Result, 1, 2, 3, 4, 5, 6, 7));
        Assert.IsNotNull(TestDataFactory.CreateTestData<int, int, int, int, int, int, int, int>(Def, Result, 1, 2, 3, 4, 5, 6, 7, 8));
        Assert.IsNotNull(TestDataFactory.CreateTestData<int, int, int, int, int, int, int, int, int>(Def, Result, 1, 2, 3, 4, 5, 6, 7, 8, 9));
    }
    #endregion

    #region TypeParams (correct concrete generic type per arity)
    [TestMethod]
    public void arity1_isInstanceOf_testDataT1()
    {
        var sut = TestDataFactory.CreateTestData<int>(Def, Result, 1);
        Assert.IsInstanceOfType<TestData<int>>(sut);
    }

    [TestMethod]
    public void arity9_isInstanceOf_testDataT1ToT9()
    {
        var sut = TestDataFactory.CreateTestData<int, int, int, int, int, int, int, int, int>(
            Def, Result, 1, 2, 3, 4, 5, 6, 7, 8, 9);
        Assert.IsInstanceOfType<TestData<int, int, int, int, int, int, int, int, int>>(sut);
    }
    #endregion

    #region ArgsList (each ArgN property stores its corresponding constructor argument)
    [TestMethod]
    public void arity9_allArgNProperties_haveExpectedValues()
    {
        var sut = TestDataFactory.CreateTestData<int, int, int, int, int, int, int, int, int>(
            Def, Result, 1, 2, 3, 4, 5, 6, 7, 8, 9);

        Assert.AreEqual(1, sut.Arg1);
        Assert.AreEqual(2, sut.Arg2);
        Assert.AreEqual(3, sut.Arg3);
        Assert.AreEqual(4, sut.Arg4);
        Assert.AreEqual(5, sut.Arg5);
        Assert.AreEqual(6, sut.Arg6);
        Assert.AreEqual(7, sut.Arg7);
        Assert.AreEqual(8, sut.Arg8);
        Assert.AreEqual(9, sut.Arg9);
    }
    #endregion

    #region BaseArgsList (each class passes prior args to its base class constructor)
    [TestMethod]
    public void arity2_isInstanceOf_arity1()
    {
        var sut = TestDataFactory.CreateTestData<int, string>(Def, Result, 1, "a");
        Assert.IsInstanceOfType<TestData<int>>(sut);
    }

    [TestMethod]
    public void arity2_arg1_isAccessibleFromBaseClass()
    {
        var sut = TestDataFactory.CreateTestData<int, string>(Def, Result, 42, "hello");
        Assert.AreEqual(42, sut.Arg1);    // Arg1 lives on TestData<T1> (base class)
        Assert.AreEqual("hello", sut.Arg2);
    }

    [TestMethod]
    public void arity9_isInstanceOf_arity1()
    {
        var sut = TestDataFactory.CreateTestData<int, int, int, int, int, int, int, int, int>(
            Def, Result, 1, 2, 3, 4, 5, 6, 7, 8, 9);
        Assert.IsInstanceOfType<TestData<int>>(sut);
    }
    #endregion

    #region TestCaseName and GetResult
    [TestMethod]
    public void testCaseName_hasFormat_definitionArrowResult()
    {
        var sut = TestDataFactory.CreateTestData<int>(Def, Result, 1);
        Assert.AreEqual($"{Def} => {Result}", sut.TestCaseName);
    }

    [TestMethod]
    public void getResult_returnsResultString()
    {
        var sut = TestDataFactory.CreateTestData<int>(Def, Result, 42);
        Assert.AreEqual(Result, sut.GetResult());
    }
    #endregion

    #region ToArgs
    [TestMethod]
    public void toArgs_instance_returnsSingleElementArray_containingInstance()
    {
        var sut = TestDataFactory.CreateTestData<int>(Def, Result, 1);
        var args = sut.ToArgs(ArgsCode.Instance, PropsCode.All);
        Assert.HasCount(1, args);
        Assert.AreSame(sut, args[0]);
    }

    [TestMethod]
    public void toArgs_properties_all_arity1_returnsTestCaseName_andArg1()
    {
        var sut = TestDataFactory.CreateTestData<int>(Def, Result, 42);
        var args = sut.ToArgs(ArgsCode.Properties, PropsCode.All);
        Assert.HasCount(2, args);
        Assert.AreEqual(sut.TestCaseName, args[0]);
        Assert.AreEqual(42, args[1]);
    }

    [TestMethod]
    public void toArgs_properties_all_arity2_returnsTestCaseName_andBothArgs()
    {
        var sut = TestDataFactory.CreateTestData<int, string>(Def, Result, 42, "hello");
        var args = sut.ToArgs(ArgsCode.Properties, PropsCode.All);
        Assert.HasCount(3, args);
        Assert.AreEqual(sut.TestCaseName, args[0]);
        Assert.AreEqual(42, args[1]);
        Assert.AreEqual("hello", args[2]);
    }

    [TestMethod]
    public void toArgs_properties_trimTestCaseName_arity1_removesTestCaseName()
    {
        var sut = TestDataFactory.CreateTestData<int>(Def, Result, 42);
        var args = sut.ToArgs(ArgsCode.Properties, PropsCode.TrimTestCaseName);
        Assert.HasCount(1, args);
        Assert.AreEqual(42, args[0]);
    }
    #endregion
}
