<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <!-- Build Settings -->
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <EnforceCodeStyleInBuild>True</EnforceCodeStyleInBuild>
    <Deterministic>true</Deterministic>
    <ContinuousIntegrationBuild Condition="'$(CI)' == 'true'">true</ContinuousIntegrationBuild>
    <UserSecretsId>92336b77-c400-443e-9ab2-8294d7dbf9af</UserSecretsId>

    <!-- Package Info -->
    <Version>2.3.0</Version>
    <Title>Portamical.MSTest</Title>
    <Authors>CsabaDu</Authors>
    <Company>CsabaDu</Company>
    <Description>MSTest 4 adapter for Portamical: Universal, identity-driven test data modeling for .NET.</Description>
    <Copyright>(c) 2026. Csaba Dudas (CsabaDu)</Copyright>

    <!-- Package Assets -->
    <PackageIcon>icon.png</PackageIcon>
    <PackageReadmeFile>README.md</PackageReadmeFile>
    <PackageLicenseFile>LICENSE.txt</PackageLicenseFile>
    <PackageRequireLicenseAcceptance>True</PackageRequireLicenseAcceptance>

    <!-- Repository -->
    <RepositoryUrl>https://github.com/CsabaDu/Portamical/tree/master/Portamical.MSTest</RepositoryUrl>
    <PackageTags>test; unittest; testdata; portable; dynamicdata; datadriven; async; mstest;</PackageTags>

    <!-- Release Notes -->
    <PackageReleaseNotes>v2.3.0
Changed

Fixed

Dependencies
- Portamical: 2.0.2 → 2.3.0</PackageReleaseNotes>

    <!-- Package Generation -->
    <GeneratePackageOnBuild>True</GeneratePackageOnBuild>
    <PackageOutputPath>$(OutputPath)</PackageOutputPath>

    <!-- Symbols -->
    <IncludeSymbols>True</IncludeSymbols>
    <SymbolPackageFormat>snupkg</SymbolPackageFormat>
  </PropertyGroup>

  <ItemGroup>
    <Content Remove="C:\Users\csd66\.nuget\packages\portamical\1.0.0\contentFiles\any\net10.0\xunit.runner.json" />
  </ItemGroup>

  <ItemGroup>
    <None Include="..\icon.png">
      <Pack>True</Pack>
      <PackagePath>\</PackagePath>
    </None>
    <None Include="..\LICENSE.txt">
      <Pack>True</Pack>
      <PackagePath>\</PackagePath>
    </None>
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.Extensions.Configuration.UserSecrets" Version="10.0.8" />
    <PackageReference Include="MSTest.TestFramework" Version="4.2.3" />
    <PackageReference Include="Portamical" Version="3.2.0" />
  </ItemGroup>

  <ItemGroup>
    <None Update="README.md">
      <Pack>True</Pack>
      <PackagePath>\</PackagePath>
    </None>
  </ItemGroup>

</Project>
