// <auto-generated>
// This file was generated by a T4 template. Do not modify directly.
// Edit TestDataReturns.tt instead.
// </auto-generated>
// SPDX-License-Identifier: MIT
// Copyright (c) 2026. Csaba Dudas (CsabaDu)

using Portamical.Core.Strategy;
using Portamical.Core.TestDataTypes.Patterns;

namespace Portamical.Core.TestDataTypes.Models.Specialized;

#region Concrete types
/// <summary>
/// Test data implementation for return-value tests with 1 additional argument(s).
/// </summary>
/// <inheritdoc cref="TestDataReturns{TStruct}"/>
/// <typeparam name="T1">The type of the first test argument.</typeparam>
public class TestDataReturns<TStruct, T1>
: TestDataReturns<TStruct>
where TStruct : struct
{
    internal TestDataReturns(
        string definition,
        TStruct expected,
        T1? arg1)
    : base(definition, expected)
    {
        Arg1 = arg1;
    }

    /// <summary>
    /// Gets the first test argument value.
    /// </summary>
    public T1? Arg1 { get; init; }

    /// <inheritdoc cref="TestDataBase.ToObjectArray(ArgsCode)" />
    protected override object?[] ToObjectArray(ArgsCode argsCode)
    => Extend(base.ToObjectArray, argsCode, Arg1);
}

/// <summary>
/// Test data implementation for return-value tests with 2 additional argument(s).
/// </summary>
/// <inheritdoc cref="TestDataReturns{TStruct}"/>
/// <typeparam name="T1">The type of the first test argument.</typeparam>
/// <typeparam name="T2">The type of the second test argument.</typeparam>
public class TestDataReturns<TStruct, T1, T2>
: TestDataReturns<TStruct, T1>
where TStruct : struct
{
    internal TestDataReturns(
        string definition,
        TStruct expected,
        T1? arg1, T2? arg2)
    : base(definition, expected, arg1)
    {
        Arg2 = arg2;
    }

    /// <summary>
    /// Gets the second test argument value.
    /// </summary>
    public T2? Arg2 { get; init; }

    /// <inheritdoc cref="TestDataBase.ToObjectArray(ArgsCode)" />
    protected override object?[] ToObjectArray(ArgsCode argsCode)
    => Extend(base.ToObjectArray, argsCode, Arg2);
}

/// <summary>
/// Test data implementation for return-value tests with 3 additional argument(s).
/// </summary>
/// <inheritdoc cref="TestDataReturns{TStruct}"/>
/// <typeparam name="T1">The type of the first test argument.</typeparam>
/// <typeparam name="T2">The type of the second test argument.</typeparam>
/// <typeparam name="T3">The type of the third test argument.</typeparam>
public class TestDataReturns<TStruct, T1, T2, T3>
: TestDataReturns<TStruct, T1, T2>
where TStruct : struct
{
    internal TestDataReturns(
        string definition,
        TStruct expected,
        T1? arg1, T2? arg2, T3? arg3)
    : base(definition, expected, arg1, arg2)
    {
        Arg3 = arg3;
    }

    /// <summary>
    /// Gets the third test argument value.
    /// </summary>
    public T3? Arg3 { get; init; }

    /// <inheritdoc cref="TestDataBase.ToObjectArray(ArgsCode)" />
    protected override object?[] ToObjectArray(ArgsCode argsCode)
    => Extend(base.ToObjectArray, argsCode, Arg3);
}

/// <summary>
/// Test data implementation for return-value tests with 4 additional argument(s).
/// </summary>
/// <inheritdoc cref="TestDataReturns{TStruct}"/>
/// <typeparam name="T1">The type of the first test argument.</typeparam>
/// <typeparam name="T2">The type of the second test argument.</typeparam>
/// <typeparam name="T3">The type of the third test argument.</typeparam>
/// <typeparam name="T4">The type of the fourth test argument.</typeparam>
public class TestDataReturns<TStruct, T1, T2, T3, T4>
: TestDataReturns<TStruct, T1, T2, T3>
where TStruct : struct
{
    internal TestDataReturns(
        string definition,
        TStruct expected,
        T1? arg1, T2? arg2, T3? arg3, T4? arg4)
    : base(definition, expected, arg1, arg2, arg3)
    {
        Arg4 = arg4;
    }

    /// <summary>
    /// Gets the fourth test argument value.
    /// </summary>
    public T4? Arg4 { get; init; }

    /// <inheritdoc cref="TestDataBase.ToObjectArray(ArgsCode)" />
    protected override object?[] ToObjectArray(ArgsCode argsCode)
    => Extend(base.ToObjectArray, argsCode, Arg4);
}

/// <summary>
/// Test data implementation for return-value tests with 5 additional argument(s).
/// </summary>
/// <inheritdoc cref="TestDataReturns{TStruct}"/>
/// <typeparam name="T1">The type of the first test argument.</typeparam>
/// <typeparam name="T2">The type of the second test argument.</typeparam>
/// <typeparam name="T3">The type of the third test argument.</typeparam>
/// <typeparam name="T4">The type of the fourth test argument.</typeparam>
/// <typeparam name="T5">The type of the fifth test argument.</typeparam>
public class TestDataReturns<TStruct, T1, T2, T3, T4, T5>
: TestDataReturns<TStruct, T1, T2, T3, T4>
where TStruct : struct
{
    internal TestDataReturns(
        string definition,
        TStruct expected,
        T1? arg1, T2? arg2, T3? arg3, T4? arg4, T5? arg5)
    : base(definition, expected, arg1, arg2, arg3, arg4)
    {
        Arg5 = arg5;
    }

    /// <summary>
    /// Gets the fifth test argument value.
    /// </summary>
    public T5? Arg5 { get; init; }

    /// <inheritdoc cref="TestDataBase.ToObjectArray(ArgsCode)" />
    protected override object?[] ToObjectArray(ArgsCode argsCode)
    => Extend(base.ToObjectArray, argsCode, Arg5);
}

/// <summary>
/// Test data implementation for return-value tests with 6 additional argument(s).
/// </summary>
/// <inheritdoc cref="TestDataReturns{TStruct}"/>
/// <typeparam name="T1">The type of the first test argument.</typeparam>
/// <typeparam name="T2">The type of the second test argument.</typeparam>
/// <typeparam name="T3">The type of the third test argument.</typeparam>
/// <typeparam name="T4">The type of the fourth test argument.</typeparam>
/// <typeparam name="T5">The type of the fifth test argument.</typeparam>
/// <typeparam name="T6">The type of the sixth test argument.</typeparam>
public class TestDataReturns<TStruct, T1, T2, T3, T4, T5, T6>
: TestDataReturns<TStruct, T1, T2, T3, T4, T5>
where TStruct : struct
{
    internal TestDataReturns(
        string definition,
        TStruct expected,
        T1? arg1, T2? arg2, T3? arg3, T4? arg4, T5? arg5, T6? arg6)
    : base(definition, expected, arg1, arg2, arg3, arg4, arg5)
    {
        Arg6 = arg6;
    }

    /// <summary>
    /// Gets the sixth test argument value.
    /// </summary>
    public T6? Arg6 { get; init; }

    /// <inheritdoc cref="TestDataBase.ToObjectArray(ArgsCode)" />
    protected override object?[] ToObjectArray(ArgsCode argsCode)
    => Extend(base.ToObjectArray, argsCode, Arg6);
}

/// <summary>
/// Test data implementation for return-value tests with 7 additional argument(s).
/// </summary>
/// <inheritdoc cref="TestDataReturns{TStruct}"/>
/// <typeparam name="T1">The type of the first test argument.</typeparam>
/// <typeparam name="T2">The type of the second test argument.</typeparam>
/// <typeparam name="T3">The type of the third test argument.</typeparam>
/// <typeparam name="T4">The type of the fourth test argument.</typeparam>
/// <typeparam name="T5">The type of the fifth test argument.</typeparam>
/// <typeparam name="T6">The type of the sixth test argument.</typeparam>
/// <typeparam name="T7">The type of the seventh test argument.</typeparam>
public class TestDataReturns<TStruct, T1, T2, T3, T4, T5, T6, T7>
: TestDataReturns<TStruct, T1, T2, T3, T4, T5, T6>
where TStruct : struct
{
    internal TestDataReturns(
        string definition,
        TStruct expected,
        T1? arg1, T2? arg2, T3? arg3, T4? arg4, T5? arg5, T6? arg6, T7? arg7)
    : base(definition, expected, arg1, arg2, arg3, arg4, arg5, arg6)
    {
        Arg7 = arg7;
    }

    /// <summary>
    /// Gets the seventh test argument value.
    /// </summary>
    public T7? Arg7 { get; init; }

    /// <inheritdoc cref="TestDataBase.ToObjectArray(ArgsCode)" />
    protected override object?[] ToObjectArray(ArgsCode argsCode)
    => Extend(base.ToObjectArray, argsCode, Arg7);
}

/// <summary>
/// Test data implementation for return-value tests with 8 additional argument(s).
/// </summary>
/// <inheritdoc cref="TestDataReturns{TStruct}"/>
/// <typeparam name="T1">The type of the first test argument.</typeparam>
/// <typeparam name="T2">The type of the second test argument.</typeparam>
/// <typeparam name="T3">The type of the third test argument.</typeparam>
/// <typeparam name="T4">The type of the fourth test argument.</typeparam>
/// <typeparam name="T5">The type of the fifth test argument.</typeparam>
/// <typeparam name="T6">The type of the sixth test argument.</typeparam>
/// <typeparam name="T7">The type of the seventh test argument.</typeparam>
/// <typeparam name="T8">The type of the eighth test argument.</typeparam>
public class TestDataReturns<TStruct, T1, T2, T3, T4, T5, T6, T7, T8>
: TestDataReturns<TStruct, T1, T2, T3, T4, T5, T6, T7>
where TStruct : struct
{
    internal TestDataReturns(
        string definition,
        TStruct expected,
        T1? arg1, T2? arg2, T3? arg3, T4? arg4, T5? arg5, T6? arg6, T7? arg7, T8? arg8)
    : base(definition, expected, arg1, arg2, arg3, arg4, arg5, arg6, arg7)
    {
        Arg8 = arg8;
    }

    /// <summary>
    /// Gets the eighth test argument value.
    /// </summary>
    public T8? Arg8 { get; init; }

    /// <inheritdoc cref="TestDataBase.ToObjectArray(ArgsCode)" />
    protected override object?[] ToObjectArray(ArgsCode argsCode)
    => Extend(base.ToObjectArray, argsCode, Arg8);
}

/// <summary>
/// Test data implementation for return-value tests with 9 additional argument(s).
/// </summary>
/// <inheritdoc cref="TestDataReturns{TStruct}"/>
/// <typeparam name="T1">The type of the first test argument.</typeparam>
/// <typeparam name="T2">The type of the second test argument.</typeparam>
/// <typeparam name="T3">The type of the third test argument.</typeparam>
/// <typeparam name="T4">The type of the fourth test argument.</typeparam>
/// <typeparam name="T5">The type of the fifth test argument.</typeparam>
/// <typeparam name="T6">The type of the sixth test argument.</typeparam>
/// <typeparam name="T7">The type of the seventh test argument.</typeparam>
/// <typeparam name="T8">The type of the eighth test argument.</typeparam>
/// <typeparam name="T9">The type of the ninth test argument.</typeparam>
public class TestDataReturns<TStruct, T1, T2, T3, T4, T5, T6, T7, T8, T9>
: TestDataReturns<TStruct, T1, T2, T3, T4, T5, T6, T7, T8>
where TStruct : struct
{
    internal TestDataReturns(
        string definition,
        TStruct expected,
        T1? arg1, T2? arg2, T3? arg3, T4? arg4, T5? arg5, T6? arg6, T7? arg7, T8? arg8, T9? arg9)
    : base(definition, expected, arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8)
    {
        Arg9 = arg9;
    }

    /// <summary>
    /// Gets the ninth test argument value.
    /// </summary>
    public T9? Arg9 { get; init; }

    /// <inheritdoc cref="TestDataBase.ToObjectArray(ArgsCode)" />
    protected override object?[] ToObjectArray(ArgsCode argsCode)
    => Extend(base.ToObjectArray, argsCode, Arg9);
}

#endregion
